name: Deploy and Validate Metadata

on:
  workflow_dispatch:  # Permet de lancer manuellement
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SFDX CLI and sfdx-git-delta plugin
        run: |
          npm install -g sfdx-cli
          echo "y" | sfdx plugins:install sfdx-git-delta@3.3.0

      - name: Authentification Salesforce
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > authfile.txt
          sfdx auth:sfdxurl:store -f authfile.txt --setdefaultusername --setalias myOrg

      - name: Generate metadata delta pull request
        run: |
          mkdir -p .delta
          git fetch origin main
          sfdx sgd:source:delta --from origin/main --to HEAD --output .delta

      - name: Deploy metadata to main
        if: github.ref == 'refs/heads/main'
        run: |
          sfdx force:source:deploy -x .delta/package/package.xml -u myOrg -w 10 --ignorewarnings