name: Salesforce CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  validate:
    if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
    name: Validate Delta on Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate with Salesforce (Dev Org)
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias devOrg --set-default

      - name: Generate Delta Package
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          mkdir -p delta
          git fetch origin $BRANCH_NAME
          git diff --name-only origin/$BRANCH_NAME...HEAD \
            | grep -E "\.(cls|trigger|page|component|xml|js|css|svg|labels|permissionset|object|field|tab|workflow|flow|resource)$" \
            | xargs -I{} cp --parents {} delta/ || echo "No changes to validate."

      - name: Check for Changes
        run: |
          if [ -z "$(ls -A delta)" ]; then
            echo "No changes detected. Skipping validation."
            exit 0
          fi

      - name: Validate Delta Metadata with Apex Tests
        run: |
          sf project deploy validate \
            --metadata-dir delta \
            --target-org devOrg \
            --test-level RunLocalTests \
            --verbose

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Deploy Delta on Main
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate with Salesforce (Prod Org)
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias prodOrg --set-default

      - name: Generate Delta Package
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          mkdir -p delta
          git fetch origin $BRANCH_NAME
          git diff --name-only origin/$BRANCH_NAME...HEAD \
            | grep -E "\.(cls|trigger|page|component|xml|js|css|svg|labels|permissionset|object|field|tab|workflow|flow|resource)$" \
            | xargs -I{} cp --parents {} delta/ || echo "No changes to deploy."

      - name: Check for Changes
        run: |
          if [ -z "$(ls -A delta)" ]; then
            echo "No changes detected. Skipping deployment."
            exit 0
          fi

      - name: Deploy Metadata with Apex Tests
        run: |
          sf project deploy start \
            --metadata-dir delta \
            --target-org prodOrg \
            --wait 10 \
            --test-level RunLocalTests \
            --ignore-warnings \
            --verbose